


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tableX.glb 
*/

import React, { useRef } from 'react'
import { Text } from 'troika-three-text';


import { useGLTF, useAnimations } from '@react-three/drei'
import Mo from './tableX.glb';
export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(Mo)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" position={[0.081, 0.042, -0.705]} rotation={[-Math.PI / 2, 0, 0]} scale={[15.841, 12.076, 12.076]}>
          <group name="32d1f6a7adc34f788e0a0f254a0f2b57fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Banner">
                  <mesh name="Banner_Banner_colour_0" geometry={nodes.Banner_Banner_colour_0.geometry} material={materials['Banner_colour.001']} />
                </group>
                <group name="Banner1">
                  <mesh name="Banner1_Banner_colour_0" geometry={nodes.Banner1_Banner_colour_0.geometry} material={materials['Banner_colour.001']} />
                </group>
                <group name="Books">
                  <group name="group1" position={[0, -1.91, 0]}>
                    <group name="Book135">
                      <mesh name="Book135_Book_All_0" geometry={nodes.Book135_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book136">
                      <mesh name="Book136_Book_All_0" geometry={nodes.Book136_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book137">
                      <mesh name="Book137_Book_All_0" geometry={nodes.Book137_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book138">
                      <mesh name="Book138_Book_All_0" geometry={nodes.Book138_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book139">
                      <mesh name="Book139_Book_All_0" geometry={nodes.Book139_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book140">
                      <mesh name="Book140_Book_All_0" geometry={nodes.Book140_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book141">
                      <mesh name="Book141_Book_All_0" geometry={nodes.Book141_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book142">
                      <mesh name="Book142_Book_All_0" geometry={nodes.Book142_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book143">
                      <mesh name="Book143_Book_All_0" geometry={nodes.Book143_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book144">
                      <mesh name="Book144_Book_All_0" geometry={nodes.Book144_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book145">
                      <mesh name="Book145_Book_All_0" geometry={nodes.Book145_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book146">
                      <mesh name="Book146_Book_All_0" geometry={nodes.Book146_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book147">
                      <mesh name="Book147_Book_All_0" geometry={nodes.Book147_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book148">
                      <mesh name="Book148_Book_All_0" geometry={nodes.Book148_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                  </group>
                  <group name="group10">
                    <group name="Book105">
                      <mesh name="Book105_Book_All_0" geometry={nodes.Book105_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book106">
                      <mesh name="Book106_Book_All_0" geometry={nodes.Book106_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book107">
                      <mesh name="Book107_Book_All_0" geometry={nodes.Book107_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book108">
                      <mesh name="Book108_Book_All_0" geometry={nodes.Book108_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book109">
                      <mesh name="Book109_Book_All_0" geometry={nodes.Book109_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                  </group>
                  <group name="group11">
                    <group name="Book115">
                      <mesh name="Book115_Book_All_0" geometry={nodes.Book115_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book116">
                      <mesh name="Book116_Book_All_0" geometry={nodes.Book116_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book117">
                      <mesh name="Book117_Book_All_0" geometry={nodes.Book117_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book118">
                      <mesh name="Book118_Book_All_0" geometry={nodes.Book118_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book119">
                      <mesh name="Book119_Book_All_0" geometry={nodes.Book119_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book120">
                      <mesh name="Book120_Book_All_0" geometry={nodes.Book120_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book121">
                      <mesh name="Book121_Book_All_0" geometry={nodes.Book121_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book122">
                      <mesh name="Book122_Book_All_0" geometry={nodes.Book122_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book123">
                      <mesh name="Book123_Book_All_0" geometry={nodes.Book123_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                  </group>
                  <group name="group12">
                    <group name="Book167">
                      <mesh name="Book167_Book_All_0" geometry={nodes.Book167_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book168">
                      <mesh name="Book168_Book_All_0" geometry={nodes.Book168_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book169">
                      <mesh name="Book169_Book_All_0" geometry={nodes.Book169_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book170">
                      <mesh name="Book170_Book_All_0" geometry={nodes.Book170_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book171">
                      <mesh name="Book171_Book_All_0" geometry={nodes.Book171_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book172">
                      <mesh name="Book172_Book_All_0" geometry={nodes.Book172_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book173">
                      <mesh name="Book173_Book_All_0" geometry={nodes.Book173_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book174">
                      <mesh name="Book174_Book_All_0" geometry={nodes.Book174_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book175">
                      <mesh name="Book175_Book_All_0" geometry={nodes.Book175_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                  </group>
                  <group name="group13">
                    <group name="Book157">
                      <mesh name="Book157_Book_All_0" geometry={nodes.Book157_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book158">
                      <mesh name="Book158_Book_All_0" geometry={nodes.Book158_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book159">
                      <mesh name="Book159_Book_All_0" geometry={nodes.Book159_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book160">
                      <mesh name="Book160_Book_All_0" geometry={nodes.Book160_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book161">
                      <mesh name="Book161_Book_All_0" geometry={nodes.Book161_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book162">
                      <mesh name="Book162_Book_All_0" geometry={nodes.Book162_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book163">
                      <mesh name="Book163_Book_All_0" geometry={nodes.Book163_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book164">
                      <mesh name="Book164_Book_All_0" geometry={nodes.Book164_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book165">
                      <mesh name="Book165_Book_All_0" geometry={nodes.Book165_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book166">
                      <mesh name="Book166_Book_All_0" geometry={nodes.Book166_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                  </group>
                  <group name="group14">
                    <group name="Book149">
                      <mesh name="Book149_Book_All_0" geometry={nodes.Book149_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book150">
                      <mesh name="Book150_Book_All_0" geometry={nodes.Book150_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book151">
                      <mesh name="Book151_Book_All_0" geometry={nodes.Book151_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book152">
                      <mesh name="Book152_Book_All_0" geometry={nodes.Book152_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book153">
                      <mesh name="Book153_Book_All_0" geometry={nodes.Book153_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book154">
                      <mesh name="Book154_Book_All_0" geometry={nodes.Book154_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book155">
                      <mesh name="Book155_Book_All_0" geometry={nodes.Book155_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book156">
                      <mesh name="Book156_Book_All_0" geometry={nodes.Book156_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                  </group>
                  <group name="group2">
                    <group name="Book84">
                      <mesh name="Book84_Book_All_0" geometry={nodes.Book84_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book85">
                      <mesh name="Book85_Book_All_0" geometry={nodes.Book85_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book86">
                      <mesh name="Book86_Book_All_0" geometry={nodes.Book86_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book87">
                      <mesh name="Book87_Book_All_0" geometry={nodes.Book87_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book88">
                      <mesh name="Book88_Book_All_0" geometry={nodes.Book88_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                  </group>
                  <group name="group3">
                    <group name="Book89">
                      <mesh name="Book89_Book_All_0" geometry={nodes.Book89_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book90">
                      <mesh name="Book90_Book_All_0" geometry={nodes.Book90_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book91">
                      <mesh name="Book91_Book_All_0" geometry={nodes.Book91_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book92">
                      <mesh name="Book92_Book_All_0" geometry={nodes.Book92_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book93">
                      <mesh name="Book93_Book_All_0" geometry={nodes.Book93_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book94">
                      <mesh name="Book94_Book_All_0" geometry={nodes.Book94_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book95">
                      <mesh name="Book95_Book_All_0" geometry={nodes.Book95_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                  </group>
                  <group name="group4">
                    <group name="Book20">
                      <mesh name="Book20_Book_All_0" geometry={nodes.Book20_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book81">
                      <mesh name="Book81_Book_All_0" geometry={nodes.Book81_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book82">
                      <mesh name="Book82_Book_All_0" geometry={nodes.Book82_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book83">
                      <mesh name="Book83_Book_All_0" geometry={nodes.Book83_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                  </group>
                  <group name="group5">
                    <group name="Book100">
                      <mesh name="Book100_Book_All_0" geometry={nodes.Book100_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book101">
                      <mesh name="Book101_Book_All_0" geometry={nodes.Book101_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book102">
                      <mesh name="Book102_Book_All_0" geometry={nodes.Book102_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book96">
                      <mesh name="Book96_Book_All_0" geometry={nodes.Book96_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book97">
                      <mesh name="Book97_Book_All_0" geometry={nodes.Book97_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book98">
                      <mesh name="Book98_Book_All_0" geometry={nodes.Book98_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book99">
                      <mesh name="Book99_Book_All_0" geometry={nodes.Book99_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                  </group>
                  <group name="group6">
                    <group name="Book103">
                      <mesh name="Book103_Book_All_0" geometry={nodes.Book103_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book104">
                      <mesh name="Book104_Book_All_0" geometry={nodes.Book104_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                  </group>
                  <group name="group7">
                    <group name="Book124">
                      <mesh name="Book124_Book_All_0" geometry={nodes.Book124_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book125">
                      <mesh name="Book125_Book_All_0" geometry={nodes.Book125_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book126">
                      <mesh name="Book126_Book_All_0" geometry={nodes.Book126_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book127">
                      <mesh name="Book127_Book_All_0" geometry={nodes.Book127_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book128">
                      <mesh name="Book128_Book_All_0" geometry={nodes.Book128_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book129">
                      <mesh name="Book129_Book_All_0" geometry={nodes.Book129_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book130">
                      <mesh name="Book130_Book_All_0" geometry={nodes.Book130_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book131">
                      <mesh name="Book131_Book_All_0" geometry={nodes.Book131_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                  </group>
                  <group name="group8">
                    <group name="Book132">
                      <mesh name="Book132_Book_All_0" geometry={nodes.Book132_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book133">
                      <mesh name="Book133_Book_All_0" geometry={nodes.Book133_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book134">
                      <mesh name="Book134_Book_All_0" geometry={nodes.Book134_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                  </group>
                  <group name="group9">
                    <group name="Book110">
                      <mesh name="Book110_Book_All_0" geometry={nodes.Book110_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book111">
                      <mesh name="Book111_Book_All_0" geometry={nodes.Book111_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book112">
                      <mesh name="Book112_Book_All_0" geometry={nodes.Book112_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book113">
                      <mesh name="Book113_Book_All_0" geometry={nodes.Book113_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                    <group name="Book114">
                      <mesh name="Book114_Book_All_0" geometry={nodes.Book114_Book_All_0.geometry} material={materials['Book_All.001']} />
                    </group>
                  </group>
                </group>
                <group name="BookShelfWall">
                  <mesh name="BookShelfWall_lambert13_0" geometry={nodes.BookShelfWall_lambert13_0.geometry} material={materials['lambert13.001']} scale={[1, 1.291, 1]} />
                </group>
                <group name="Carpet" />
                <group name="Curtains">
                  <group name="curtains">
                    <mesh name="curtains_Curtains_colour_0" geometry={nodes.curtains_Curtains_colour_0.geometry} material={materials['Curtains_colour.001']} />
                  </group>
                  <group name="curtains1">
                    <mesh name="curtains1_Curtains_colour_0" geometry={nodes.curtains1_Curtains_colour_0.geometry} material={materials['Curtains_colour.001']} />
                  </group>
                  <group name="curtains2">
                    <mesh name="curtains2_Curtains_colour_0" geometry={nodes.curtains2_Curtains_colour_0.geometry} material={materials['Curtains_colour.001']} />
                  </group>
                  <group name="curtains3">
                    <mesh name="curtains3_Curtains_colour_0" geometry={nodes.curtains3_Curtains_colour_0.geometry} material={materials['Curtains_colour.001']} />
                  </group>
                  <group name="RedCurtain" />
                </group>
                <group name="Dust_Specs">
                  <group name="pCube1" position={[-2.459, 9.917, -39.158]} scale={0}>
                    <mesh name="pCube1_lambert1_0" geometry={nodes.pCube1_lambert1_0.geometry} material={materials['lambert1.001']} position={[-393216, 246128, 14313697]} />
                  </group>
                  <group name="pCube10" position={[-0.474, 12.085, -40.08]} scale={0}>
                    <mesh name="pCube10_lambert1_0" geometry={nodes.pCube10_lambert1_0.geometry} material={materials['lambert1.001']} position={[0, 1450179.5, -10486632]} />
                  </group>
                  <group name="pCube2" position={[-0.763, 9.313, -40.266]} scale={0}>
                    <mesh name="pCube2_lambert1_0" geometry={nodes.pCube2_lambert1_0.geometry} material={materials['lambert1.001']} position={[-32768, 3578552.5, 1628880.75]} />
                  </group>
                  <group name="pCube3" position={[0.445, 9.313, -39.451]} scale={0}>
                    <mesh name="pCube3_lambert1_0" geometry={nodes.pCube3_lambert1_0.geometry} material={materials['lambert1.001']} position={[0, 1344109, -2565423.5]} />
                  </group>
                  <group name="pCube4" position={[1.129, 9.803, -39.809]} scale={0}>
                    <mesh name="pCube4_lambert1_0" geometry={nodes.pCube4_lambert1_0.geometry} material={materials['lambert1.001']} position={[0, 355914.5, -6677102.5]} />
                  </group>
                  <group name="pCube5" position={[-0.066, 10.714, -39.866]} scale={0}>
                    <mesh name="pCube5_lambert1_0" geometry={nodes.pCube5_lambert1_0.geometry} material={materials['lambert1.001']} position={[32768, 1414039.5, -10717792]} />
                  </group>
                  <group name="pCube7" position={[-0.763, 10.075, -39.46]} scale={0}>
                    <mesh name="pCube7_lambert1_0" geometry={nodes.pCube7_lambert1_0.geometry} material={materials['lambert1.001']} position={[-32768, 297021.5, 1757381]} />
                  </group>
                  <group name="pCube8" position={[-1.667, 8.806, -39.946]} scale={0}>
                    <mesh name="pCube8_lambert1_0" geometry={nodes.pCube8_lambert1_0.geometry} material={materials['lambert1.001']} position={[131072, 1427468, 1543510]} />
                  </group>
                  <group name="pCube9" position={[-1.563, 10.581, -39.518]} scale={0}>
                    <mesh name="pCube9_lambert1_0" geometry={nodes.pCube9_lambert1_0.geometry} material={materials['lambert1.001']} position={[0, 1355311, 1842660.875]} />
                  </group>
                </group>
                <group name="Floor">
                  <mesh name="Floor_floor_colour_0" geometry={nodes.Floor_floor_colour_0.geometry} material={materials['floor_colour.001']} />
                </group>
                <group name="GlowingChest" />
                <group name="GreekPillars">
                  <group name="GreekPillar">
                    <mesh name="GreekPillar_Pillar_Colour_0" geometry={nodes.GreekPillar_Pillar_Colour_0.geometry} material={materials['Pillar_Colour.001']} />
                  </group>
                  <group name="GreekPillar1">
                    <mesh name="GreekPillar1_Pillar_Colour_0" geometry={nodes.GreekPillar1_Pillar_Colour_0.geometry} material={materials['Pillar_Colour.001']} />
                  </group>
                  <group name="GreekPillar2">
                    <mesh name="GreekPillar2_Pillar_Colour_0" geometry={nodes.GreekPillar2_Pillar_Colour_0.geometry} material={materials['Pillar_Colour.001']} />
                  </group>
                  <group name="GreekPillar3">
                    <mesh name="GreekPillar3_Pillar_Colour_0" geometry={nodes.GreekPillar3_Pillar_Colour_0.geometry} material={materials['Pillar_Colour.001']} />
                  </group>
                  <group name="GreekPillar4">
                    <mesh name="GreekPillar4_Pillar_Colour_0" geometry={nodes.GreekPillar4_Pillar_Colour_0.geometry} material={materials['Pillar_Colour.001']} />
                  </group>
                </group>
                <group name="group" position={[-3.396, 0, 75.659]}>
                  <group name="pasted__LightRays" position={[0.84, -0.689, -46.299]} rotation={[-0.009, -0.001, 0.199]} scale={0.431}>
                    <mesh name="pasted__LightRays_pasted__Rays_Mat_0" geometry={nodes.pasted__LightRays_pasted__Rays_Mat_0.geometry} material={materials['pasted__Rays_Mat.001']} />
                  </group>
                  <group name="pasted__LightRays1" position={[1.084, -0.858, -68.878]} rotation={[-0.02, -0.005, 0.452]} scale={0.431}>
                    <mesh name="pasted__LightRays1_pasted__Rays_Mat_0" geometry={nodes.pasted__LightRays1_pasted__Rays_Mat_0.geometry} material={materials['pasted__Rays_Mat.001']} />
                  </group>
                  <group name="pasted__LightRays2" position={[-0.119, -2.228, -88.629]} rotation={[-0.014, -0.002, 0.32]} scale={0.431}>
                    <mesh name="pasted__LightRays2_pasted__Rays_Mat_0" geometry={nodes.pasted__LightRays2_pasted__Rays_Mat_0.geometry} material={materials['pasted__Rays_Mat.001']} />
                  </group>
                  <group name="pasted__LightRays3" position={[-5.225, -2.228, -109.021]} rotation={[-0.014, -0.002, 0.32]} scale={0.431}>
                    <mesh name="pasted__LightRays3_pasted__Rays_Mat_0" geometry={nodes.pasted__LightRays3_pasted__Rays_Mat_0.geometry} material={materials['pasted__Rays_Mat.001']} />
                  </group>
                </group>
                <group name="MainCurtainHolders" />
                <group name="MiniChest">
                  <mesh name="MiniChest_lambert17_0" geometry={nodes.MiniChest_lambert17_0.geometry} material={materials['lambert17.001']} />
                </group>
                <group name="MiniChest1">
                  <mesh name="MiniChest1_lambert17_0" geometry={nodes.MiniChest1_lambert17_0.geometry} material={materials['lambert17.001']} />
                </group>
                <group name="PaintingWall">
                  <mesh name="PaintingWall_painting_wall_0" geometry={nodes.PaintingWall_painting_wall_0.geometry} material={materials['painting_wall.001']} position={[1.88, -0.286, -0.071]} scale={[1.071, 1.31, 1]} />
                  <mesh name="PaintingWall_painting_wall_0001" geometry={nodes.PaintingWall_painting_wall_0001.geometry} material={materials['painting_wall.001']} position={[0.812, -9.033, -43.442]} rotation={[1.562, 0.014, 0]} scale={[1.083, 3.278, 1]} />
                  <mesh name="PaintingWall_painting_wall_0002" geometry={nodes.PaintingWall_painting_wall_0002.geometry} material={materials['painting_wall.001']} position={[0.252, 33.623, -0.41]} rotation={[3.114, 0, 0]} scale={[1.071, 1.31, 1]} />
                </group>
                <group name="Stairs">
                  <mesh name="Stairs_Stairs_Colour_0" geometry={nodes.Stairs_Stairs_Colour_0.geometry} material={materials['Stairs_Colour.001']} />
                </group>
                <group name="Torch_Fire_Plains">
                  <group name="Torch_Fire1" />
                  <group name="Torch_Fire2" />
                </group>
                <group name="Torches">
                  <group name="Torch" />
                  <group name="Torch1" />
                </group>
                <group name="Vase">
                  <mesh name="Vase_vase_colour_0" geometry={nodes.Vase_vase_colour_0.geometry} material={materials['vase_colour.001']} />
                </group>
                <group name="Vase1">
                  <mesh name="Vase1_vase_colour_0" geometry={nodes.Vase1_vase_colour_0.geometry} material={materials['vase_colour.001']} />
                </group>
                <group name="Vase2">
                  <mesh name="Vase2_vase_colour_0" geometry={nodes.Vase2_vase_colour_0.geometry} material={materials['vase_colour.001']} />
                </group>
                <group name="Wall_length">
                  <mesh name="Wall_length_left_wall_0" geometry={nodes.Wall_length_left_wall_0.geometry} material={materials['left_wall.001']} scale={[1, 1.119, 1]} />
                </group>
                <group name="WindowFrame">
                  <group name="Window_Frame">
                    <mesh name="Window_Frame_Window_colour_0" geometry={nodes.Window_Frame_Window_colour_0.geometry} material={materials['Window_colour.001']} />
                  </group>
                  <group name="Window_Frame1">
                    <mesh name="Window_Frame1_Window_colour_0" geometry={nodes.Window_Frame1_Window_colour_0.geometry} material={materials['Window_colour.001']} />
                  </group>
                  <group name="Window_Frame2">
                    <mesh name="Window_Frame2_Window_colour_0" geometry={nodes.Window_Frame2_Window_colour_0.geometry} material={materials['Window_colour.001']} />
                  </group>
                  <group name="Window_Frame3">
                    <mesh name="Window_Frame3_Window_colour_0" geometry={nodes.Window_Frame3_Window_colour_0.geometry} material={materials['Window_colour.001']} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model001" position={[-0.035, 0.07, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.776, 1.318, 1.074]}>
          <group name="db8ebb0038d04f7fa283de5eee7d9334fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
            <group name="RootNode001">
              <group name="ACTR_LOGO012" position={[-749.297, 748.903, -1212.962]} rotation={[0, -1.571, 0]} scale={[0.713, 0.713, 3.681]}>

              </group>
              <group name="ACTR_LOGO016" position={[764.782, 749.746, -1144.349]} rotation={[0, 1.571, 0]} scale={[0.791, 0.791, 2.027]}>
                <group name="Object_49" position={[2229.109, -999.294, 342.4]}>
                  <mesh name="ACTR_LOGO016_CIZGI_0" geometry={nodes.ACTR_LOGO016_CIZGI_0.geometry} material={materials['CIZGI.001']} />
                </group>
              </group>
              <group name="ACTR_LOGO017" position={[-749.471, 749.746, 1385.109]} rotation={[0, -1.571, 0]} scale={[0.791, 0.791, 2.027]}>
                <group name="Object_79" position={[2229.107, -999.293, 342.4]}>
                  <mesh name="ACTR_LOGO017_CIZGI_0" geometry={nodes.ACTR_LOGO017_CIZGI_0.geometry} material={materials['CIZGI.001']} />
                </group>
              </group>
              <group name="ACTR_LOGO018" position={[629.725, 60.485, 558.132]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ACTR_LOGO018_aaa_0" geometry={nodes.ACTR_LOGO018_aaa_0.geometry} material={materials['material_15.001']} />
              </group>
              <group name="ACTR_LOGO019" position={[-638.37, 60.485, -107.575]} rotation={[-Math.PI / 2, 0, Math.PI]}>
                <mesh name="ACTR_LOGO019_aaa_0" geometry={nodes.ACTR_LOGO019_aaa_0.geometry} material={materials['material_15.001']} />
              </group>

              <group name="Box099" position={[5.961, 694.809, 114.751]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-1}>
                <mesh name="Box099_09_-_Default_0" geometry={nodes['Box099_09_-_Default_0'].geometry} material={materials['09_-_Default.001']} position={[1.681, 0, 0]} scale={[0.993, 1, 1]} />
              </group>
              <group name="Box102" position={[115.336, 536.632, 48.619]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.993, -1, -1]}>
                <mesh name="Box102_Wood067_2K_0" geometry={nodes.Box102_Wood067_2K_0.geometry} material={materials['Wood067_2K.001']} />
              </group>
              <group name="Box104" position={[32.284, 183.18, -584.75]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Box104_MASA_ALT_BLOK_0" geometry={nodes.Box104_MASA_ALT_BLOK_0.geometry} material={materials['MASA_ALT_BLOK.001']} position={[1.49, 0, 0]} scale={[0.993, 1, 1]} />
              </group>
              <group name="Box105" position={[101.944, -365.904, 351.596]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.494, 1, 1]}>
                <mesh name="Box105_MASA_ALT_BLOK_0" geometry={nodes.Box105_MASA_ALT_BLOK_0.geometry} material={materials['MASA_ALT_BLOK.001']} />
              </group>
              <group name="Box106" position={[22.106, 183.18, 338.589]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Box106_07_-_Default_0" geometry={nodes['Box106_07_-_Default_0'].geometry} material={materials['07_-_Default.001']} position={[1.564, 0, 0]} scale={[0.993, 1, 1]} />
              </group>
              <group name="Box107" position={[-262.646, 183.18, 338.589]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Box107_07_-_Default_0" geometry={nodes['Box107_07_-_Default_0'].geometry} material={materials['07_-_Default.001']} />
              </group>
              <group name="NET" position={[8.102, 835.005, 116.915]} rotation={[-Math.PI / 2, 0, 0]}>
                <group name="ACTR_LOGO014" position={[-717.586, 3.564, 72.531]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.451, 0.451, 1.163]}>
                  <group name="Object_59" position={[2229.109, -999.293, 342.4]}>
                    <mesh name="ACTR_LOGO014_C_WOOD_0" geometry={nodes.ACTR_LOGO014_C_WOOD_0.geometry} material={materials['C_WOOD.001']} />
                  </group>
                </group>
                <group name="ACTR_LOGO015" position={[715.15, -6.916, 72.531]} rotation={[Math.PI / 2, 0, 0]} scale={[0.448, 0.451, 1.163]}>
                  <group name="Object_56" position={[2229.109, -999.293, 342.4]}>
                  </group>
                </group>
                <group name="Box108" position={[-8.438, 0, -39.055]} rotation={[Math.PI, 0, 0]} scale={-0.156}>
                  <group name="Object_74" position={[-344.103, 0, -277.568]} scale={[0.993, 1, 1]} />
                </group>
                <group name="Object057" position={[1.665, -1.811, 72.225]} rotation={[0, 0, -Math.PI]} scale={[0.993, 1, 1]}>
                  <group name="Object_65" position={[0, 0, -142.421]}>
                    <mesh name="Object057_Metal045A_2K_0" geometry={nodes.Object057_Metal045A_2K_0.geometry} material={materials['Metal045A_2K.001']} position={[7.057, -6.138, 43.453]} />
                  </group>
                </group>

                <group name="Object061" position={[0, -1.811, 20.975]} rotation={[0, 0, -Math.PI]}>
                  <group name="Object_62" position={[-1.665, 0, -91.171]} scale={[0.993, 1, 1]} />
                </group>
                <group name="Object063" position={[1.665, -1.811, 72.225]} rotation={[0, 0, -Math.PI]} scale={[0.993, 1, 1]}>
                  <group name="Object_68" position={[0, 0, -142.421]}>
                    <mesh name="Object063_Metal045A_2K_0" geometry={nodes.Object063_Metal045A_2K_0.geometry} material={materials['Metal045A_2K.001']} />
                  </group>
                </group>
                <group name="Object064" position={[-8.438, 0, -39.055]} rotation={[Math.PI, 0, 0]} scale={-0.156}>
                  <group name="Object_53" position={[-344.103, 0, -277.569]} scale={[0.993, 1, 1]} />
                </group>
              </group>
              <group name="Object045" position={[-69.451, 4.809, 39.009]} rotation={[-Math.PI / 2, 0, 0]}>
                <group name="Object_15" position={[2635.442, -3064.835, 1337.494]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1.266, -0.217, -0.539]} />
              </group>
              <group name="Object046" position={[5.961, 734.809, 114.751]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Object046_01_0" geometry={nodes.Object046_01_0.geometry} material={materials['material_7.001']} />
                <mesh name="Object046_02_0" geometry={nodes.Object046_02_0.geometry} material={materials['material_8.001']} />
                <mesh name="Object046_03_0" geometry={nodes.Object046_03_0.geometry} material={materials['material.001']} />
              </group>
              <group name="Object047" position={[750.247, 734.809, 114.751]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Object047_01_0" geometry={nodes.Object047_01_0.geometry} material={materials['material_7.001']} position={[-3.713, 0, 0]} scale={[0.993, 1, 1]} />
                <mesh name="Object047_02_0" geometry={nodes.Object047_02_0.geometry} material={materials['material_8.001']} position={[-3.713, 0, 0]} scale={[0.993, 1, 1]} />
                <mesh name="Object047_03_0" geometry={nodes.Object047_03_0.geometry} material={materials['material.001']} position={[-3.713, 0, 0]} scale={[0.993, 1, 1]} />
              </group>
              <group name="Object048" position={[5.961, 734.809, 1471.413]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Object048_01_0" geometry={nodes.Object048_01_0.geometry} material={materials['material_7.001']} />
                <mesh name="Object048_02_0" geometry={nodes.Object048_02_0.geometry} material={materials['material_8.001']} />
                <mesh name="Object048_03_0" geometry={nodes.Object048_03_0.geometry} material={materials['material.001']} />
              </group>
              <group name="Object049" position={[750.247, 734.809, 1471.413]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Object049_01_0" geometry={nodes.Object049_01_0.geometry} material={materials['material_7.001']} position={[-3.713, 0, 0]} scale={[0.993, 1, 1]} />
                <mesh name="Object049_02_0" geometry={nodes.Object049_02_0.geometry} material={materials['material_8.001']} position={[-3.713, 0, 0]} scale={[0.993, 1, 1]} />
                <mesh name="Object049_03_0" geometry={nodes.Object049_03_0.geometry} material={materials['material.001']} position={[-3.713, 0, 0]} scale={[0.993, 1, 1]} />
              </group>
              <group name="Object050" position={[5.961, 734.809, 114.751]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Object050_01_0" geometry={nodes.Object050_01_0.geometry} material={materials['material_7.001']} position={[1.681, 0, 0]} scale={[0.993, 1, 1]} />
                <mesh name="Object050_CIZGI_0" geometry={nodes.Object050_CIZGI_0.geometry} material={materials['CIZGI.001']} position={[1.681, 0, 0]} scale={[0.993, 1, 1]} />
              </group>
              <group name="Object051" position={[115.336, 536.632, 48.619]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-0.993, -1, -1]}>
                <mesh name="Object051_LIGHT_0" geometry={nodes.Object051_LIGHT_0.geometry} material={materials['LIGHT.001']} />
              </group>
              <group name="Object052" position={[32.284, 183.18, -584.75]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Object052_MetalPlates006_2K_0" geometry={nodes.Object052_MetalPlates006_2K_0.geometry} material={materials['MetalPlates006_2K.001']} position={[1.49, 0, 0]} scale={[0.993, 1, 1]} />
              </group>
              <group name="Text001" position={[763.119, 740.199, -1198.195]} rotation={[0, 1.571, 0]} scale={[1, 1, 0.993]}>
                <mesh name="Text001_CIZGI_0" geometry={nodes.Text001_CIZGI_0.geometry} material={materials['CIZGI.001']} />
              </group>
              <group name="Text002" position={[-754.984, 740.199, 1438.955]} rotation={[0, -1.571, 0]}>
                <mesh name="Text002_CIZGI_0" geometry={nodes.Text002_CIZGI_0.geometry} material={materials['CIZGI.001']} />
              </group>
              <group name="Text003" position={[624.354, 29.878, 385.505]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Text003_aaa_0" geometry={nodes.Text003_aaa_0.geometry} material={materials['material_15.001']} position={[-2.801, 0, 0]} scale={[0.993, 1, 1]} />
              </group>
              <group name="Text004" position={[621.553, 29.878, -267.801]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.993, 1, 1]}>
                <mesh name="Text004_aaa_0" geometry={nodes.Text004_aaa_0.geometry} material={materials['material_15.001']} />
              </group>
              <group name="Text005" position={[-632.999, 29.878, 65.052]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh name="Text005_aaa_0" geometry={nodes.Text005_aaa_0.geometry} material={materials['material_15.001']} />
              </group>
              <group name="Text006" position={[-632.999, 29.878, 718.358]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh name="Text006_aaa_0" geometry={nodes.Text006_aaa_0.geometry} material={materials['material_15.001']} />
              </group>
              <group name="Text006YAZI004" position={[-755.964, 740.254, -1174.55]} rotation={[0, -1.571, 0]} scale={[1, 1, 5.203]}>
                <mesh name="Text006YAZI004_Metal045A_2K_0" geometry={nodes.Text006YAZI004_Metal045A_2K_0.geometry} material={materials['Metal045A_2K.001']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Object_97" position={[-79.369, 155.135, -34.58]} />
        <group name="Box002" position={[0.627, 43.774, 2.529]} rotation={[0, 0, -Math.PI / 2]} scale={0.466} />
        <group name="Box004" position={[0.627, 43.774, -2.529]} rotation={[0, 0, Math.PI / 2]} scale={-0.466} />
        <group name="Box005" position={[0.627, 43.774, -3.673]} rotation={[0, 0, Math.PI / 2]} scale={-0.466} />
        <group name="Object_108" position={[-79.369, 155.135, -34.58]} />
        <group name="Box001" position={[0.627, 43.774, -2.529]} rotation={[0, 0, -Math.PI / 2]} scale={0.466} />
        <group name="Box006" position={[0.627, 43.774, 3.673]} rotation={[0, 0, -Math.PI / 2]} scale={0.466} />
        <group name="Box007" position={[0.627, 43.774, -2.529]} rotation={[0, 0, -Math.PI / 2]} scale={0.466} />
        <group name="Box008" position={[0.627, 43.774, 1.648]} rotation={[0, 0, -Math.PI / 2]} scale={0.466} />
        <group name="Object112" position={[51.741, 0, 4.817]} rotation={[0, 0, -Math.PI / 2]} scale={0.466}>
          <group name="Object_121" position={[-93.867, -109.603, -2.453]} />
        </group>
        <group name="Box109" position={[0.627, 43.774, -2.529]} rotation={[0, 0, -Math.PI / 2]} scale={0.466} />
        <group name="Box110" position={[0.627, 43.774, 2.529]} rotation={[0, 0, -Math.PI / 2]} scale={0.466} />
        <group name="Box111" position={[0.627, 43.774, -2.529]} rotation={[0, 0, Math.PI / 2]} scale={-0.466} />
        <group name="Box112" position={[0.627, 43.774, -3.673]} rotation={[0, 0, Math.PI / 2]} scale={-0.466} />
        <group name="Box113" position={[0.627, 43.774, 3.673]} rotation={[0, 0, -Math.PI / 2]} scale={0.466} />
        <group name="Box114" position={[0.627, 43.774, -2.529]} rotation={[0, 0, -Math.PI / 2]} scale={0.466} />
        <group name="Box115" position={[0.627, 43.774, 1.648]} rotation={[0, 0, -Math.PI / 2]} scale={0.466} />
        <group name="Object_141" position={[-79.369, 155.135, -34.58]} />
        <group name="Object114" position={[-71.718, 6.761, -3.951]} rotation={[0, 0, Math.PI / 2]} scale={-0.466}>
          <group name="Object_146" position={[-79.369, 155.135, -34.58]} />
        </group>
        <group name="Object_151" position={[-93.867, -109.603, -2.453]} />
        <group name="Sketchfab_model002" position={[0.048, 0.456, -5.317]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.215, 1, 1.244]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Ancient_Greek_Bust_Type_A_Destroyed_01_3" position={[0.634, 0, 0]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Ancient_Greek_Bust_Type_A_Marble.001']} />
              </group>
              <group name="Ancient_Greek_Bust_Type_A_Destroyed_02_4" position={[0.924, 0, 0]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Ancient_Greek_Bust_Type_A_RoughStone.001']} />
              </group>
              <group name="Ancient_Greek_Bust_Type_A_Faux_Bronze_6" position={[-0.297, 0, 0]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['Ancient_Greek_Bust_Type_A_Faux_Bronze.001']} />
              </group>
              <group name="Ancient_Greek_Bust_Type_A_Marble_5" position={[-0.615, 0, 0]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['Ancient_Greek_Bust_Type_A_Marble.001']} />
              </group>
              <group name="Ancient_Greek_Bust_Type_A_Pose_02_1" position={[0.001, 0, 0]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Ancient_Greek_Bust_Type_A_RoughStone.001']} />
              </group>
              <group name="Ancient_Greek_Bust_Type_A_Pose_03_2" position={[0.324, 0, 0]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Ancient_Greek_Bust_Type_A_RoughStone.001']} />
              </group>
              <group name="Ancient_Greek_Bust_Type_A_RoughStone_0" position={[-0.925, 0, 0]}>
                <mesh name="Object_4001" geometry={nodes.Object_4001.geometry} material={materials['Ancient_Greek_Bust_Type_A_RoughStone.001']} />
              </group>
            </group>
          </group>
        </group>
        <mesh name="soa001" geometry={nodes.soa001.geometry} material={materials['soa.001']} position={[0.001, 2.029, 4.437]} rotation={[1.523, 0.011, -3.138]} scale={[3.398, 0.827, 3.218]} />
        <mesh name="philosophers_playing" geometry={nodes.philosophers_playing.geometry} material={materials['philosophers playing']} position={[0, 2.193, -5.889]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[3.435, 1, 3.435]} />
        <mesh name="Text" geometry={nodes.Text.geometry} material={materials['Material.001']} position={[-0.958, 0.961, 0.165]} rotation={[1.613, 0, 0]} scale={[0.299, 0.997, 0.13]} />
      

      </group>

    </group>
  )
}

useGLTF.preload(Mo)
